apiVersion: v1
kind: Pod
metadata:
  name: my-python-app
spec:
  containers:
    - name: my-python-container
      image: <your_docker_image_name>:<tag>
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "172.17.0.2"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: APP_COLOR
          value: "blue"
